// ===================================================================
// YOUR PHOTOS GO HERE.
// One entry per photo.
//
// src      -> path to the image file inside the /images folder
//             (must match your actual filename EXACTLY, including capitalization)
// category -> must be one of: local, convention, stage
//             (these power the filter buttons)
// featured -> set to true to have this photo show up in the Favorites section
// ===================================================================
const photos = [
  { src: "images/Photo-01.jpg", category: "convention", featured: true },
  { src: "images/Photo-02.jpg", category: "convention", featured: false },
  { src: "images/Photo-03.jpg", category: "convention", featured: false },
  { src: "images/Photo-04.jpg", category: "convention", featured: true },
  { src: "images/Photo-05.jpg", category: "convention", featured: false },
  { src: "images/Photo-06.jpg", category: "convention", featured: false },
  { src: "images/Photo-07.jpg", category: "convention", featured: false },
  { src: "images/Photo-08.jpg", category: "convention", featured: false },
  { src: "images/Photo-09.jpg", category: "convention", featured: false },
  { src: "images/Photo-10.jpg", category: "local", featured: false },
  { src: "images/Photo-11.jpg", category: "local", featured: false },
  { src: "images/Photo-12.jpg", category: "convention", featured: false },
  { src: "images/Photo-13.jpg", category: "convention", featured: true },
  { src: "images/Photo-14.jpg", category: "convention", featured: false },
  { src: "images/Photo-15.jpg", category: "convention", featured: false },
  { src: "images/Photo-16.jpg", category: "convention", featured: false },
  { src: "images/Photo-17.jpg", category: "local", featured: false },
  { src: "images/Photo-18.jpg", category: "local", featured: false },
  { src: "images/Photo-19.jpg", category: "local", featured: true },
  { src: "images/Photo-20.jpg", category: "convention", featured: false },
  { src: "images/Photo-21.jpg", category: "convention", featured: false },
  { src: "images/Photo-22.jpg", category: "convention", featured: false },
  { src: "images/Photo-23.jpg", category: "local", featured: false },
  { src: "images/Photo-24.jpg", category: "local", featured: false },
  { src: "images/Photo-25.jpg", category: "convention", featured: false },
  { src: "images/Photo-26.jpg", category: "convention", featured: false },
  { src: "images/Photo-27.jpg", category: "convention", featured: false },
  { src: "images/Photo-28.jpg", category: "local", featured: false },
  { src: "images/Photo-29.jpg", category: "local", featured: false },
  { src: "images/Photo-30.jpg", category: "local", featured: true },
  { src: "images/Photo-31.jpg", category: "convention", featured: false },
  { src: "images/Photo-32.jpg", category: "convention", featured: false },
  { src: "images/Photo-33.jpg", category: "local", featured: true },
  { src: "images/Photo-34.jpg", category: "local", featured: false },
  { src: "images/Photo-35.jpg", category: "local", featured: false },
  { src: "images/Photo-36.jpg", category: "convention", featured: false },
  { src: "images/Photo-37.jpg", category: "local", featured: false },
  { src: "images/Photo-38.jpg", category: "local", featured: true },
  { src: "images/Photo-39.jpg", category: "local", featured: false },
  { src: "images/Photo-40.jpg", category: "local", featured: true },
  { src: "images/Photo-41.jpg", category: "local", featured: false },
  { src: "images/Photo-42.jpg", category: "local", featured: false },
  { src: "images/Photo-43.jpg", category: "local", featured: false },
  { src: "images/Photo-44.jpg", category: "local", featured: false },
  { src: "images/Photo-45.jpg", category: "local", featured: true },
  { src: "images/Photo-46.jpg", category: "local", featured: false },
  { src: "images/Photo-47.jpg", category: "convention", featured: false },
  { src: "images/Photo-48.jpg", category: "convention", featured: true },
  { src: "images/Photo-50.jpg", category: "convention", featured: false },
  { src: "images/Photo-51.jpg", category: "convention", featured: false },
  { src: "images/Photo-52.jpg", category: "convention", featured: false },
  { src: "images/Photo-53.jpg", category: "convention", featured: false },
  { src: "images/Photo-54.jpg", category: "convention", featured: false },
  { src: "images/Photo-55.jpg", category: "stage", featured: false },
  { src: "images/Photo-56.jpg", category: "stage", featured: false },
  { src: "images/Photo-57.jpg", category: "stage", featured: false },
  { src: "images/Photo-58.jpg", category: "stage", featured: false },
  { src: "images/Photo-59.jpg", category: "stage", featured: false },
  { src: "images/Photo-60.jpg", category: "stage", featured: false },
  { src: "images/Photo-61.jpg", category: "convention", featured: true },
  { src: "images/Photo-62.jpg", category: "convention", featured: false },
  { src: "images/Photo-63.jpg", category: "convention", featured: false },
  { src: "images/Photo-64.jpg", category: "convention", featured: true },
  { src: "images/Photo-65.jpg", category: "convention", featured: false },
];
